---
- name: Restart PRTG probe
  hosts: PRTG_DEV
  gather_facts: no
  tasks:
    - name: Run PowerShell Script
      win_shell: |
        D:\PRTG_Recycle\PRTG_Recycle.ps1
      register: script_output
      ignore_errors: yes

    - name: Debug output
      debug:
        var: script_output.stdout

    - name: Check for ParseError and display success message
      debug:
        msg: "Script ran successfully despite the ParseError."
      when: script_output.msg is defined and ("ParseError" in script_output.msg or "no element found" in script_output.msg)

    - name: Fail task if no ParseError is found
      fail:
        msg: "Unexpected success: The script should have produced a ParseError."
      when: script_output.msg is not defined or not ("ParseError" in script_output.msg or "no element found" in script_output.msg)
