---
- name: Restart PRTG probe
  hosts: PRTG_DEV
  gather_facts: yes
  tasks:
    - name: Execute PowerShell script
      win_command: |
        D:\PRTG_Recycle\PRTG_Recycle.ps1
      register: script_output
      
    - name: Display script output
      debug:
        var: script_output.stdout_lines
