---
- name: Restart PRTG probe
  hosts: all
  gather_facts: yes
  tasks:
    - name: Execute PowerShell script
      win_shell: |
        # Path to the PowerShell script
        D:\PRTG_Recycle\PRTG_Recycle.ps1
      register: script_output
      when: environment == 'DEV'

    - name: Display script output
      debug:
        var: script_output.stdout_lines
      when: environment == 'DEV'
