---
- name: Restart PRTG probe
  hosts: PRTG_DEV
  gather_facts: no
  tasks:
    - name: Run PowerShell Script
      win_command: powershell.exe -ExecutionPolicy Bypass -File "D:\PRTG_Recycle\PRTG_Recycle.ps1"
