---
- name: Restart PRTG probe
  hosts: PRTG_DEV
  gather_facts: no
  tasks:
    - name: Run PowerShell Script
      win_shell: |
        D:\PRTG_Recycle\PRTG_Recycle.ps1
    - name: Debug output
      debug:
        var: script_output.stdout

    - name: Debug error
      debug:
        var: script_output.stderr
