---
- name: Restart PRTG probe
  hosts: PRTG_DEV
  gather_facts: yes
  tasks:
    - name: Execute PowerShell script
      ansible.windows.win_shell: |
        powershell.exe -File D:\PRTG_Recycle\PRTG_Recycle.ps1 >  D:\PRTG_Recycle\output.txt 2>&1
      register: script_output
      ignore_errors: yes
      
    - name: Read the output file
      ansible.windows.win_slurp:
        src: D:\PRTG_Recycle\output.txt
      register: output_file

    - name: Display script output from file
      debug:
        msg: "{{ output_file.content | b64decode }}"
